(function($){
    $(function(){

        var dogs = [
            {'Name': 'Adina Monsoon',
             'Notes': 'OLR. HW+. Has started to become bitey with people handling her-be careful/go slow. Per sleepover notes, RG of her bed.',
             'Scores': {},
             'Shelterluv data': false,
             'Updated': '12/4/2016'},
            {'Name': 'Babyface',
             'Notes': 'Prone to overarousal; cuddly and affectionate with those he knows. Walks well on leash around ballfields. Should be only dog in home.',
             'Scores': {'Cat': '1', 'Child': '2', 'Dog': '2', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/29/2016'},
            {'Name': 'Bandit',
             'Notes': 'Previous owner said he had bitten 4 people (adults & kids), but not reported. Potential separation anxiety. Best in home with older kids (14+). Good with other dogs in the shelter.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '9/19/2016'},
            {'Name': 'Banjo',
             'Notes': 'Knows tricks. Loves treats. Was CGC Ready. No dogs. Very easy on leash and great with new people. Not reactive on leash. Hospice case.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/9/2016'},
            {'Name': 'Bear',
             'Notes': 'No dogs. No kids. Resource guarder, Painful hips/ Handling sensitivity. Go slow with new people.',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/9/2016'},
            {'Name': 'Beckie',
             'Notes': 'No home notes. Has been snuggly here but sometimes sensitive about collar/ butt scratches. Heartworm +. Bad bite incident from sticking fingers in kennel.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/18/2016'},
            {'Name': 'Bevo',
             'Notes': 'Resource guarder (people). Does great in PG.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/18/2016'},
            {'Name': 'Blanket',
             'Notes': 'No apartments. Low traffic home. Must go home with another dog, very shy but friendly with his people. Per foster, strong prey drive towards cats.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '5', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '11/29/2016'},
            {'Name': 'Blue (Unavailable)',
             'Notes': 'Lived with horses, handling sensitivity, good with dogs. No kids. Smart boy. Fearful of new people. Go slow. ',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '4', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '9/19/2016'},
            {'Name': 'Bock',
             'Notes': '*VIRTUAL FOSTER* No kids. Loves fetch. Knows sit/down/drop/shake. House/crate trained. Caution with strangers.',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/18/2016'},
            {'Name': 'Boscoe',
             'Notes': '*VIRTUAL FOSTER* Resource Guards grass. Needs a DL on at all times. No dogs, No kids. GL on corkboard. Take to Davenport for potential adopters. Do not let off leash. Allow him to meet potential adopters one at a time. Stress increases at the sight of another dog. Treat like silver in kennel, orange outside.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '10/24/2016'},
            {'Name': 'Brasco',
             'Notes': 'Defensive in kennel. No dogs. Potentially older kids. Crate-trained & seems housetrained. Can be nervous meeting new people. Loves fetch. Very affectionate once hes comfortable',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '1', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/18/2016'},
            {'Name': 'Briah',
             'Notes': 'Needs low-traffic home due to territorial behavior. Housebroken and Crate-trained. Knows sit, stay, down, come, leave it. Possible resource guarding. On leash reactivity to other dogs. Very sweet and affectionate with her people.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/23/2016'},
            {'Name': 'Brimmer',
             'Notes': 'Would benefit from a lower traffic home or a home with a yard. Has shown strong reactivity to people (mostly men) on walks. Also has sep. anxiety and RG-ing reported in the previous home.  House & crate trained.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '1', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/18/2016'},
            {'Name': 'Brindle',
             'Notes': 'Walks great on leash around ballfields. Very sweet. Housetrained and cratetrained. Knows sit, stay, down shake (per previous owner.) Does not appear to be good with small dogs. Has shown strong BR reactivity to children. Chases cats & squirrels. Resource guarding from other dog in previous home.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '2', 'Home': '5'},
             'Shelterluv data': true,
             'Updated': '11/7/2016'},
            {'Name': 'Bruce',
             'Notes': "Very sweet boy. Lived with dogs in previous home, but doesn't do great in PG here. Lived with kids and did well. Previous home noted he was housetrained and crate-trained, but exhibited separation anxiety in foster home.",
             'Scores': {'Cat': '1', 'Child': '4', 'Dog': '3', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/28/2016'},
            {'Name': 'Bullet G',
             'Notes': 'Previous notes of potential handling sensitivites that resulted in a bite history. Does good with dogs, older kids only. Territorial behavior in previous home.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/9/2016'},
            {'Name': 'Captain Jack',
             'Notes': 'Territorial issues in previous home. Low traffic. No kids. All adults in household meet him before he goes home. ',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '2', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/9/2016'},
            {'Name': 'Celina',
             'Notes': 'Sep. anxiety in previous home. No dogs. High energy. Loves fetch. CGC trainee!\n',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '1', 'Home': '2'},
             'Shelterluv data': true,
             'Updated': '11/18/2016'},
            {'Name': 'Cersi',
             'Notes': 'Territorial behavior in home. Did not get along well with dogs in home. Possibly older children.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '10/17/2016'},
            {'Name': 'Chalupa',
             'Notes': 'Loves fetch! Territorial in home - low-traffic home. Handler protection. Has done well being shown to people at TLAC. Does well in PG',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '4', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/18/2016'},
            {'Name': 'Chance (UNAVAILABLE)',
             'Notes': '',
             'Scores': {},
             'Shelterluv data': false,
             'Updated': '11/28/2016'},
            {'Name': 'Charlotte',
             'Notes': 'Super boo. RG-ing of space/food/toys to other dogs in previous foster home. Did some damage to foster dogs over a resource. Needs to be the only dog in the home. Nondestructive in the home. ',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '1', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '10/17/2016'},
            {'Name': 'Chewy',
             'Notes': "Pretty playful (PG2) in yard with some rough and rowdy play. Vision issues. Previously was getting amped up in his kennel but hasn't been an issue recently with various handlers. Loves fetch! HW+",
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '9/1/2016'},
            {'Name': 'Choko Bell',
             'Notes': ' *VIRTUAL FOSTER* Territorial in the home. Low-traffic, adult only home. OLR to dogs & people. Affectionate with those he knows.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/18/2016'},
            {'Name': 'Christian',
             'Notes': 'Low-traffic, adult-only home. 1-2 people max (no roommates). No apartments, no kids. Refer people to Carrie to introduce.',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/9/2016'},
            {'Name': 'Chubbs',
             'Notes': 'Territorial issues in previous home - low-traffic needed. No kids. All adults in household must meet him before he goes home. Handling sensitivity when reached for too quickly. Love fetch!',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '8/15/2016'},
            {'Name': 'Clark',
             'Notes': '*VIRTUAL FOSTER* Territorial behaviors in home, issues when approached on leash. More fearful of men. Bite history. Mixed notes with cats. Housetrained, but has separation anxiety (breaking out of crate in previous home).',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '2', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/29/2016'},
            {'Name': 'Coco',
             'Notes': 'Lockhart space intake. Potential flight risk behaviors while out for PGA-was defensive/shy with assesment dogs ',
             'Scores': {},
             'Shelterluv data': false,
             'Updated': '/2016'},
            {'Name': 'Coconut ',
             'Notes': 'Low-traffic, No other animals in the home. Lived with kids before, but displayed territorial behaviors in recent home.',
             'Scores': {'Cat': '1', 'Child': '3', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/14/2016'},
            {'Name': 'Colt',
             'Notes': ' CGC Ready! Housetrained. Crate Trained. Loves water. Loves people. Doing ok with slow intros to cats.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/16/2016'},
            {'Name': 'Colt',
             'Notes': ' CGC Ready! Housetrained. Crate Trained. Loves water. Loves people. Doing ok with slow intros to cats. Returned due to overarousal.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/29/2016'},
            {'Name': 'Cookie',
             'Notes': 'Territorial in the home, No kids, low traffic home with a yard. Like fetch. Currently working with a behavior buddy on his skills. Preadoption training required.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '8/15/2016'},
            {'Name': 'Cosmo',
             'Notes': 'Crate & house-trained. CGC trainee. Likes fetch.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '1', 'Home': '4'},
             'Shelterluv data': false,
             'Updated': '10/11/2016'},
            {'Name': 'Daisy',
             'Notes': 'Housebroken and has done well in home on sleepovers. Very sweet. HW+',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '2', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '9/22/2016'},
            {'Name': 'Darwin',
             'Notes': 'Older kids only. Returned most recently for biting child in face. Was alone with child in kitchen who was getting food and touch Darwin. Bite was moderate to severe. Resource guards with other dogs, will need a heavy consult if going home with another dog, but is probably best as the only dog. High energy and has struggled with leash climbing here in the past but appears to be getting somewhat better.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/23/2016'},
            {'Name': 'Dodger',
             'Notes': '*VIRTUAL FOSTER* No dogs. Housetrained and quiet in the home. Would need slow intos to new people in the home. OLR to dogs. Went on a sleepover with a CAT and did well. Shows promise with cats but keeping at a 3 score',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '1', 'Home': '5'},
             'Shelterluv data': false,
             'Updated': '11/11/2016'},
            {'Name': 'Dr. Pepper',
             'Notes': 'Jumpy puppy. Leash climber.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/28/2016'},
            {'Name': 'Dude',
             'Notes': 'Returned due to separation anxiety in previous home (barking, howling, whining). Loves to fetch and walk on trail (per previous owner). Does well in PG.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '4', 'Home': '2'},
             'Shelterluv data': false,
             'Updated': '11/9/2016'},
            {'Name': 'Ebert ',
             'Notes': '*VIRTUAL FOSTER* No kids. No dogs. Knows sit and stay. Resource guarder. Escape artist. Take to Davenport with potential adopters.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '8/15/2016'},
            {'Name': 'Faraon',
             'Notes': 'Resource guarding from other dogs. Territorial behaviors in home. No kids. Low-traffic home.',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '2', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/9/2016'},
            {'Name': 'Freya',
             'Notes': 'CGC trainee! Can be dog reactive. Loves toys. High energy girl. Shows better outside of the shelter - Davenport or walking around ballfields.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '2', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/29/2016'},
            {'Name': 'Galaxy',
             'Notes': 'Mandatory Pre-Adoption training. No apartments. No kids, no roommates, everyone must meet dog. She was protective of handler in previous home and had strong territorial behaviors. OLR to dogs and people. ',
             'Scores': {'Cat': '2', 'Child': '1', 'Dog': '2', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '8/18/2016'},
            {'Name': 'Garrison (Unavailable)',
             'Notes': 'Pre/post adopt training, very low traffic home(two people max), house. Smart and has a lot of training behind him. Could be a running buddy. Is okay with people outside of home.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '1', 'Home': '4'},
             'Shelterluv data': false,
             'Updated': '8/18/2016'},
            {'Name': 'Garth',
             'Notes': 'No home notes.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '11/28/2016'},
            {'Name': 'Gibson',
             'Notes': 'No dogs. Appears housetrained. Very sweet.',
             'Scores': {'Cat': '3', 'Child': '4', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '10/24/2016'},
            {'Name': 'Gilbert',
             'Notes': 'Ask staff before taking out. History of JAMy behavior/ possible resource guarding of blankets. Caution with strangers. Currently he is not allowed to have anyone approach him, not even his friends, while he is on leash. He loves rope toys. He seems ok with the crate and will sometimes walk into an open crate and lay down.  Introduce to potential adopters in Davenport - more playful in there.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '2', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/8/2016'},
            {'Name': 'Grizzle',
             'Notes': 'No Kids. Heartworm +. Seems housetrained. Probably would prefer to be the only dog. Has been uncomfortable around dogs in PG. Crate Trained. Knows place, sit and shake. Two bites on record. One that seems to be from handling sensitivity around having his EZ walk put on in his kennel. The other "nipped face" in home without a lot of context. Has done really well meeting people here outside of that and outside of TLAC with his behavior buddy. But seems to be vary wary of MEN. Lunged at man (from a distance) walking through TLAC.',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '3', 'Home': '4'},
             'Shelterluv data': false,
             'Updated': '11/1/2016'},
            {'Name': 'Harley',
             'Notes': '',
             'Scores': {},
             'Shelterluv data': false,
             'Updated': '11/28/2016'},
            {'Name': 'Hoffman',
             'Notes': 'Bite History in previous home with a special needs child. Home with older children? Has been overall easy to handle at TLAC. Knows sit',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/28/2016'},
            {'Name': 'Huggy',
             'Notes': 'Mostly deaf! Go slow! Nervous of new people, especially with petting. Housebroken and crate-trained but occasionally destructive when left alone uncrated. Guarding of people and space in previous home. No apartments. Can and will jump a 4 ft fence. Low traffic house. No kids. No dogs because she will guard people from other dogs.',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '1', 'Home': '2'},
             'Shelterluv data': true,
             'Updated': '10/17/2016'},
            {'Name': 'Icicle',
             'Notes': 'Go slow! Nervous of new people. Reportedly killed another dog, but had lived with other dogs in previous home.',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '10/17/2016'},
            {'Name': 'Jazzy',
             'Notes': 'Transfer from Georgetown. No home notes.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '10/31/2016'},
            {'Name': 'Jeffree',
             'Notes': 'Very boo. Go SLOW. Would do best in a home without children.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/29/2016'},
            {'Name': 'Jester',
             'Notes': 'Has displayed territorial behavior in previous home. Low-traffic home. CGC trainee! Lived with kids previously and did well. Would recommend older kids only due to size/energy level.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '2', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '11/9/2016'},
            {'Name': 'Jimbo',
             'Notes': 'Loves fetch. Careful with ears. CGC trainee. Heartworm + Best to show outside of kennel since he looks like a super jerk in his kennel',
             'Scores': {'Cat': '2', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/22/2016'},
            {'Name': 'Jolie',
             'Notes': 'Housetrained. Cuddly and affectionate, per previous owner. Loves toys. Defensive around other dogs in PG. No reactivity to other dogs on walks outside of TLAC. No butt prompts - sensitivity.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/16/2016'},
            {'Name': 'Kahlua',
             'Notes': 'Lived with elderly cat in home, but chases outdoor cats. High prey drive towards squirrels & small dogs. No infants or toddlers - could live with older kids. Likes water & balls. Knows sit and shake!',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '1', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/22/2016'},
            {'Name': 'King',
             'Notes': 'Loves fetch! May benefit from a lower traffic home-does have a few bites on record that could be stranger danger related. Could go home with a well-matched dog (female). RTR. Loves fetch.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '2', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '11/9/2016'},
            {'Name': 'Kona',
             'Notes': 'No small dogs. Not super playful, but gets along with dogs her size or bigger.  No apartments. Territorial behavior in home and on leash in home settings. ',
             'Scores': {'Cat': '1', 'Child': '3', 'Dog': '4', 'Home': '5'},
             'Shelterluv data': false,
             'Updated': '10/10/2016'},
            {'Name': 'La Croix',
             'Notes': 'Just weaned pups. Ringworm. RTR. Heartworm +.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '11/9/2016'},
            {'Name': 'Lamar',
             'Notes': 'Seems housetrained. Appears more weary of men. Does great in play group. Gets along well with small dogs. RTR. Bite history.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/22/2016'},
            {'Name': 'Lexi',
             'Notes': 'knows sit and shake',
             'Scores': {},
             'Shelterluv data': false,
             'Updated': '/2016'},
            {'Name': 'Lincoln',
             'Notes': 'Housebroken. Overarousal. No small kids. Likes fetch! Would do better shown to adopters in Davenport. Very strong.',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': false,
             'Updated': '11/9/2016'},
            {'Name': 'Loki',
             'Notes': 'Needs structured introductions (Check it out drill) No dogs. No kids. No apartments - territorial.',
             'Scores': {'Cat': '1', 'Child': '2', 'Dog': '1', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/22/2016'},
            {'Name': 'Lola',
             'Notes': '* VIRTUAL FOSTER* No kids. Loves treats. Doesnt like to be touched. Mellow. Easy on leash. Did find co-existing with dog inside of foster home',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '1', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/22/2016'},
            {'Name': 'MacGyver',
             'Notes': 'Seems housetrained.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '10/5/2016'},
            {'Name': 'Major',
             'Notes': 'Preadopt training required, Very intelligent. Knows shake and sit. Low-traffic adult only home with a yard. No roommates; a single person or couple. Escape artist--squeezed under fence to kill chickens in a previous home. Resource guarder.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '1', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '10/17/2016'},
            {'Name': 'Marilla',
             'Notes': 'Resource guarder. House/kennel trained. Heartworm +. Lived outside in previous home and rarely met people (7 yrs). Pulls heavily toward cats.',
             'Scores': {'Cat': '2', 'Child': '2', 'Dog': '1', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/29/2016'},
            {'Name': 'Marmalade',
             'Notes': 'Likes fetch/swimming. BX History from a stranger petting her while she was sitting with her previous owner at a cafe. Go slow when interacting with new people.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/23/2016'},
            {'Name': 'Max',
             'Notes': '*VIRTUAL FOSTER* Behavior Staff must show to potential adopters. Needs a No kids, low traffic house. Caution with strangers in any shared entryways/elevators/stairwells/etc. What we\'ve seen is that when greetings with Max are too rushed, Max can become defensive. We actually believe this behavior may be rooted in some amount of "herding" instincts, given his herding breed look and personality. ',
             'Scores': {'Cat': '2', 'Child': '1', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': false,
             'Updated': '10/17/2016'},
            {'Name': 'Maxwell',
             'Notes': 'Lockhart space pull. No home or dog notes',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '12/1/2016'},
            {'Name': 'Midas',
             'Notes': 'Loves fetch. CGC Trainee. Possible leash climber.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/22/2016'},
            {'Name': 'Mona',
             'Notes': 'Has worked on getting overstimulated/leashclimbing in the past, but has had LOTS of work in this area and doing much better now. High energy. Mostly housetrained.',
             'Scores': {'Cat': '1', 'Child': '2', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '10/24/2016'},
            {'Name': 'Monty',
             'Notes': ' History of defensive behavior and handling sensitivities. Dog-dog resource guarding shown in home.  Defensive behavior around humans in past.',
             'Scores': {'Cat': '1', 'Child': '2', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/22/2016'},
            {'Name': 'Moose',
             'Notes': '* VIRTUAL FOSTER* No toys due to overarousal, but loves fetch. OK to play fetch wih adopters. Seems housetrained.',
             'Scores': {'Cat': '2', 'Child': '2', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/22/2016'},
            {'Name': 'Morgan (unavailable)',
             'Notes': 'Approved handlers only, DEAF',
             'Scores': {'Dog': 'Unavailable'},
             'Shelterluv data': false,
             'Updated': '10/24/2016'},
            {'Name': 'Nexus(Unavailable)',
             'Notes': '*VIRTUAL FOSTER* Approved handlers only; resource guarder, leash climber, do NOT use aversives! close in neighbors, MRKR. Has had lots of on leash and polite greeting training. Needs to live in low-traffic home, could be apartment with the right set up(not a lot of shared hallways/walkways).',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '2', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '9/21/2016'},
            {'Name': 'Norman',
             'Notes': 'Walks well on leash with GDC. Not very OLR if keep 20 ft bubble. Smart and sweet boy! Great in home. Shows promise in crate, left alone for 2.5 hours in cratew/ no anxiety.  House trained. Loves playing in yard, hide & seek, zoomies, and fetch. Perfect in house, slept in bed w/ no issues. Can be JAM but stops immediately with eheh and just showing the spray  bottle.  Should not be left alone outside, will entertain himself with digging.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '1', 'Home': '4'},
             'Shelterluv data': false,
             'Updated': '11/9/2016'},
            {'Name': 'Oliver',
             'Notes': '*VIRTUAL FOSTER* No dogs. No kids. Can get overstimulated with people. LOTS OF SKILLS (sit, down, shake, recall, friendly greeting). Much better on leash too. Separation anxiety.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '2', 'Home': '2'},
             'Shelterluv data': false,
             'Updated': '10/24/16/2016'},
            {'Name': 'Oscar',
             'Notes': 'OLR to people & dogs. Resource guarder, territorial behavior in previous home, caution meeting new people. Low-traffic, adult-only home. ',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '3', 'Home': '4'},
             'Shelterluv data': false,
             'Updated': '10/24/2016'},
            {'Name': 'Paloma',
             'Notes': 'High HW+ No home notes. Very sweet girl.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/22/2016'},
            {'Name': 'Patches',
             'Notes': ' House trained. Loves to swim. Non Destructive while on sleepovers-but never left alone. Shy with new people. Warms up to women faster. Shows better in Davenport.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': false,
             'Updated': '10/24/2016'},
            {'Name': 'Payton ',
             'Notes': ' He MUST go home to a single person or couple in a house-No kids. He has severe territorial issues and some handling issues. He will be mandatory pre-adopt training. Recommending no dogs but could potentially with the right fit.',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '10/24/2016'},
            {'Name': 'Perla (UNAVAILABLE)',
             'Notes': 'No dogs. No kids. OLR to dogs. Knows "sit, stay, come, lay down." Housetrained. Resource guarder.',
             'Scores': {},
             'Shelterluv data': false,
             'Updated': '10/11/2016'},
            {'Name': 'Picasso',
             'Notes': "Returned for getting into fights with resident male dog. Didn't stop once fight got started. (Got along fine with female dog). Somewhat housetrained - not good when left alone longer than 4 hours. Crate trained. Previous owner said good with kids (6-12) and likes to snuggle.",
             'Scores': {'Cat': '3', 'Child': '4', 'Dog': '2', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/29/2016'},
            {'Name': 'Pietro',
             'Notes': "Loves water, fetch and walking on the trail. Housetrained & crate-trained. Mixed notes with kids - one owner said he didn't like small kids, other owner said he was amazing with kids.",
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '5'},
             'Shelterluv data': true,
             'Updated': '11/9/2016'},
            {'Name': 'Pinball',
             'Notes': "extremely territorial. Think of her a lot like Garrison, low traffic and adult only. No roommates! Potentially has the ability to live with other dogs. Apartments that are open to the outdoors may be acceptable, but not ideal. Pre-adopt required if you feel like the people aren't listening to you, but she will definitely be a post adoption training through our department.",
             'Scores': {},
             'Shelterluv data': false,
             'Updated': '11/9/2016'},
            {'Name': 'PJ',
             'Notes': 'No home notes. Leash climber/Redirection risk here. Has been sweet with staff',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/22/2016'},
            {'Name': 'Prieta',
             'Notes': 'Pre-adopt training is required. Slow introductions. Low traffic home with yard. No kids. No animals.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '10/24/2016'},
            {'Name': 'Pumpernickel',
             'Notes': 'Loves fetch & tennis balls! Knows sit, down, shake, high five. Housetrained. Resource guards with dogs. Previous owner noted some territorial behavior in home. Older kids only.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/23/2016'},
            {'Name': 'Quin',
             'Notes': 'Surrendered due to getting into fights with other resident female dog. Seems housetrained and crate-trained, per previous owner.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/29/2016'},
            {'Name': 'Randall',
             'Notes': 'Uncomfortable with men approaching while on leash. Bite history from chasing after someone on bike.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '10/11/2016'},
            {'Name': 'Ranger Rick',
             'Notes': 'Plays fetch! Has quite a bit of training behind him. No dogs. Needs to be the only dog in a lower traffic adult only home. Some territorial and guarding behaviors seen in previous home. No guarding behaviors seen here.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '8/18/2016'},
            {'Name': 'Reggie',
             'Notes': 'Sensitive ears/neck area. Has had quite a bit of training by volunteers to desensitize the ears/neck area and is doing well. Nothing medically wrong it seems. No smaller kids. Has done well meeting people and with people petting the rest of his body.  ',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '10/11/2016'},
            {'Name': 'Ren',
             'Notes': 'Sweet with people. Reactive to other dogs.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '11/9/2016'},
            {'Name': 'Rocky',
             'Notes': '*VIRTUAL FOSTER* Can be head shy. Heartworm +. Housetrained. Rough play style, can be mouthy. Sweet and cuddly. RTR, but has sore hips.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '10/24/2016'},
            {'Name': 'Roger',
             'Notes': 'Needs low traffic adult only home. Needs to do check it out drill with new people. MM and BEH intros only. Intros are specific to this dog. Everyone is house needs to meet before going home. No cats due to prey drive. No kids due to handling issues. Loves to play fetch with tennis balls.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '2', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '11/18/2016'},
            {'Name': 'Rolo',
             'Notes': "Hasn't been around dogs/cats in home. Is crate trained, but crate was used as form of punishment in previous home. ",
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/22/2016'},
            {'Name': 'Roxy (unavailable)',
             'Notes': "*VIRTUAL FOSTER* BEHAVIOR STAFF ONLY. low traffic home, we're thinking of her as a more territorial dog, as well. No kids, no dogs, does well when left alone in a crate. Apartment that opens up to the outside acceptable, but not ideal. Needs to be a low traffic apartment area.",
             'Scores': {},
             'Shelterluv data': false,
             'Updated': '/2016'},
            {'Name': 'Rufus (unavailable)',
             'Notes': '*VIRTUAL FOSTER* Neck and collar sensitivity. Uncomfortable with equipment. RG of food/toys/bones toward human and dogs.',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '10/17/2016'},
            {'Name': 'Santana',
             'Notes': "No dogs. No kids. Very sweet and kissy with her people. Go slow meeting new people. Doesn't like ears touched. Housetrained.",
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '1', 'Home': '4'},
             'Shelterluv data': false,
             'Updated': '11/9/2016'},
            {'Name': 'Scooby ',
             'Notes': 'No kids. Resource Guarder over rawhides in the home. Intense OLR to children and dogs. Super JAMMY behaviors in home. Antagonistic play with dogs and picks fights.',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/22/2016'},
            {'Name': 'Sheldon',
             'Notes': 'No dogs. No Kids.  Guarded home from dogs. Knows sit, stay, down & shake. Lived in a home for 7 years. Based on previous owner notes, slow to warm up to strangers, particularly entering home. Recommended that he meets all family members prior to adoption. Go slow. Housetrained, but possible separation anxiety and destructive behaviors. Returned for not getting along with resident dog-RG-ing. Orange RTR.',
             'Scores': {'Cat': '1', 'Child': '2', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '10/18/2016'},
            {'Name': 'Sophie',
             'Notes': '*VIRTUAL FOSTER* Barrier reactive to dogs. CGC Trainee! Heartworm +. Low-traffic home needed. Territorial behavior. Could live with older kids.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '11/7/2016'},
            {'Name': 'Spanky',
             'Notes': 'No dogs. No kids. Sweet and affectionate with his people. Potential guarding of handler in previous home',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '1', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '11/29/2016'},
            {'Name': 'Stimpy',
             'Notes': 'Sweet with people. Reactive to other dogs.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': false,
             'Updated': '11/9/2016'},
            {'Name': 'Sylvester',
             'Notes': 'HW+; Geriatric dog with an old leg injury.',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/7/2016'},
            {'Name': 'Tank Girl ',
             'Notes': 'Previous adopter noted very loyal and active couch potato. No cats. No small dogs. Has done well with kids. Separation anxiety. Jumpy, but loves to give kisses and get belly rubs.',
             'Scores': {'Cat': '1', 'Child': '4', 'Dog': '2', 'Home': '2'},
             'Shelterluv data': true,
             'Updated': '11/29/2016'},
            {'Name': 'Terrance',
             'Notes': "*VIRTUAL FOSTER*  Behavior Team only. In 'foster' with Gabryelle. Crate trained! Older children and potentially could go home with a super social female. ",
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': false,
             'Updated': '8/27/2016'},
            {'Name': 'Tiger',
             'Notes': ' Housetrained & cratetrained. JAMY. Owned for 2 years then surrendered because owner could no longer care for him. No dogs due to rude, rowdy play.',
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '1', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '11/29/2016'},
            {'Name': 'Timmy',
             'Notes': "Handling sensitivies. Doesn't like to be pet. Bites in previous home. Housetrained per previous owner.",
             'Scores': {'Cat': '3', 'Child': '2', 'Dog': '3', 'Home': '4'},
             'Shelterluv data': false,
             'Updated': '11/7/2016'},
            {'Name': 'Trent (UNAVAILABLE)',
             'Notes': '',
             'Scores': {},
             'Shelterluv data': false,
             'Updated': '11/9/2016'},
            {'Name': 'Trey',
             'Notes': '*VIRTUAL FOSTER* Territorial, separation anxiety, comes with indestructible crate. Great trail dog. No kids. Loves his people.',
             'Scores': {'Cat': '1', 'Child': '1', 'Dog': '2', 'Home': '2'},
             'Shelterluv data': true,
             'Updated': '9/26/2016'},
            {'Name': 'Venus',
             'Notes': 'Go slow with new people. Housetrained, not crate trained. Loves water (according to previous owner). Knows sit, down, shake and stay. Resource guarding with dogs in previous home. Several bites (not serious) of strangers in and out of home when they went to reach for her. Has not been around children.',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '2', 'Home': '5'},
             'Shelterluv data': true,
             'Updated': '11/9/2016'},
            {'Name': 'Viking',
             'Notes': 'Caution with strangers, check it out drills. Lower traffic home; territorial aggression in home. OLR. Does well with other dogs. Housetrained.',
             'Scores': {'Cat': '2', 'Child': '1', 'Dog': '4', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '10/24/2016'},
            {'Name': 'Wilma',
             'Notes': 'No home notes. Returned due to family emergency/ leaving town. Lived with another dog previously. Does well in PG',
             'Scores': {'Cat': '3', 'Child': '3', 'Dog': '3', 'Home': '3'},
             'Shelterluv data': true,
             'Updated': '11/28/2016'},
            {'Name': 'Ziggy',
             'Notes': 'Pre-adopt training required. Resource Guarder.  No apartments, no kids, low traffic home. Territorial aggression inside and outside of the home. House with yard. \n',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '2', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '8/15/2016'},
            {'Name': 'Zoe',
             'Notes': 'Pre-adoption training required. No kids - Low traffic. Guarder.',
             'Scores': {'Cat': '3', 'Child': '1', 'Dog': '3', 'Home': '4'},
             'Shelterluv data': true,
             'Updated': '9/28/2016'},
            {'Name': 'Finna',
             'Notes': 'kmows sit and to wait at doors',
             'Scores': {},
             'Shelterluv data': false,
             'Updated': '/2016'}
        ];

        var options = {
            include: ["score"],
            shouldSort: true,
            threshold: 0.6,
            location: 0,
            distance: 100,
            maxPatternLength: 32,
            keys: [
                "Name"
            ]
        };
        var fuse = new Fuse(dogs, options); 
        $('#info').hide();

        $('#search').keydown(function() {
            var result = fuse.search(this.value);
            if (!result[0]) {
                $('#info').hide();
                return;
            };
            display_info(result[0]["item"]);
        });
        
        $('#search_form').submit(
            function(event) {
                event.preventDefault();
            }
        );

        var recognition = new webkitSpeechRecognition();
        recognition.interimResults = true;

        $("#mic").bind("touchstart click", function() {
            final_transcript = '';
            recognition.start();
        });

        // $("#mic").click(function() {
        //    // event.preventDefault();
        //     $("#foo").text("click!");
        //     final_transcript = '';
        //     recognition.start();
        // });

        recognition.onstart = function() {
            console.log("Starting");
        };
        recognition.onresult = function(event) {
            console.log("onresult");
            var interim_transcript = '';

            for (var i = event.resultIndex; i < event.results.length; ++i) {
                if (event.results[i].isFinal) {
                    final_transcript += event.results[i][0].transcript;
                } else {
                    interim_transcript += event.results[i][0].transcript;
                }
            }
            $('#search').focus();
            $('#search').val(final_transcript);
            $('#search').trigger(jQuery.Event('keydown', { which: 13 }));
            console.log(final_transcript);
        };

        recognition.onerror = function(event) {
            console.log(event);
            console.log("onerror");
        };
        recognition.onend = function() {
            console.log("onend");
        };
        
    }); // end of document ready
})(jQuery); // end of jQuery name space


function display_info(dog) {
    $('#info').show();
    $('#dog_name').text(dog["Name"]);
    $('#dog_score').text(dog["Scores"]["Dog"] || "--");
    $('#child_score').text(dog["Scores"]["Child"] || "--");
    $('#cat_score').text(dog["Scores"]["Cat"] || "--");
    $('#home_score').text(dog["Scores"]["Home"] || "--");
    $('#notes').text(dog["Notes"]);
    $('#updated').text(dog["Updated"]);
    if (dog["Shelterluv data"]) {
        $('#sl').text('✓');
    } else {
        $('#sl').text('');
    }
};
